const ADD_MASSAGE = "ADD_MASSAGE"
const CREATE_MASSAGELIST = "CREATE_MASSAGELISST"
const DELETE_MASSAGE = "DELETE_MASSAGE"
const DELETE_MASSAGELIST = "DELETE_MASSAGELIST"

export { ADD_MASSAGE, CREATE_MASSAGELIST, DELETE_MASSAGE, DELETE_MASSAGELIST }